title:       Leader's Digest
email:       benjamin@squeakyvessel.com
author:      Benjamin Reitzammer
description: "Leader's Digest - Shortest & Quickest Weekly Newsletter about Leadership in Tech"
baseurl:     "/"
url:         "http://leaders-dige.st"

markdown: kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink: /:year/:month/:day/:title/
paginate: 5
sass:
  compressed: true
